### ISSUE TITLE
Latest v2.0 not dectected DAWs

### ISSUE THREAD

**Issue by No06LuSec** [lmharpae/DAWRPC#10]
Hello,
I downloaded the latest DAWRPC v2.0 and executed it before opening S1, Ableton. But it seems like it doesn't detect S1 or Ableton.
I checked and tried troubleshooting according to [Issue#4](https://github.com/lmharpae/DAWRPC/issues/4) and [Issue#6](https://github.com/lmharpae/DAWRPC/issues/6) that you mentioned, but it still doesn't get the DAWRPC v2.0 working. Pls help.
![image](https://github.com/lmharpae/DAWRPC/assets/32434689/ba9d0e9f-b2ca-47e4-8783-2a3c3c78b5c7)
![image](https://github.com/lmharpae/DAWRPC/assets/32434689/ed2dd6c8-96fa-47ea-b566-9f3419571ef8)

**Comment by lmharpae** [comment]
Sorry for the late reply.
This error could be due to my other Discord account's deletion, so the Application ID for Ableton Live 11 Suite and Studio One on Discord weren't able to use anymore.
I will change the Application ID and release a fix soon. Thank you for reporting this issue.
