### ISSUE TITLE
REAPER 

### ISSUE THREAD

**Issue by githubanal** [lmharpae/DAWRPC#7]
reaper is not displayed on any version of dawrpc

**Comment by PerfectFyfth** [comment]
I have been having the same issue. DawRCP shows a status for Live, FL, and Bitwig, but not REAPER. While the program itself detects REAPER, it doesn't display it as a status over Discord.

**Comment by sidoka-contact** [comment]
same here

**Comment by ping-mee** [comment]
same here

**Comment by lemonekq** [comment]
same

**Comment by GronyRalph** [comment]
same

**Comment by KingLucasz** [comment]
same
