### ISSUE TITLE
is it possible to run it in the background fully without it being in some corner of my screen?

### ISSUE THREAD

**Issue by therealjackbuilder** [lmharpae/DAWRPC#8]
when i minimize it, it seems to just shorten down to a bar.
![image](https://github.com/NozakiYuu/DAWRPC/assets/97404484/50b662d8-60a9-4ec6-8622-275e624417e2)

is it possible to automatically start it in the background, without it taking up screen space and forget about it?

also, if there is an option to remove cpu usage from discord rpc, that would be amazing as well.

**Comment by NozakiYuu** [comment]
Yes, I will definitely do it in the next version. Sorry for keeping you waiting.
